<header>
    <div id="main_header">
        <a id="logo" href="index.php"><img src="./images/Glory_logo.png" alt="logo"></a>
        <div id="search">
            <form method="get">
                <input type="text" placeholder="Search here...">
                <button type="submit">Search</button>
            </form>                   
        </div>
        <a id="cart" href=""><img src="./images/shopping-cart-black-shape.png" alt="cart"><p>Cart</p></a>
        <div id="login_register">
            <a href="">Login</a>
            <a href="">Register</a>
        </div>
    </div>          
    <nav>
        <div id="main_nav">
            <ul>
                <li>
                    <a href="product.php">Product</a>
                    <!--Dropdown menu-->
                    <ul class="sub_menu">                                
                        <li><a href="">Sofa</a></li>
                        <li><a href="">Table</a></li>
                        <li><a href="">Lighting</a></li>
                        <li><a href="">Door</a></li>
                    </ul>
                </li>
                <li><a href="">Contact</a></li>
                <li><a href="about.php">About us</a></li>
                <li>
                    <a href="">Enhancement</a>
                    <ul class="sub_menu">                                
                        <li><a href="enhancement.php">Enhancement 1</a></li>
                        <li><a href="enhancement2.php">Enhancement 2</a></li>                      
                    </ul>
                </li>
                <li>
                    <a href="">Video</a>
                    <ul class="sub_menu">                                
                        <li><a href="https://youtu.be/lfe5Ren0JAQ">Video 1</a></li>
                        <li><a href="https://youtu.be/R1yPrc9LbdM">Video 2</a></li>                      
                    </ul>
                </li>
                <li><a href="manager.php">Manager</a></li>
            </ul>                  
        </div>
    </nav>                  
</header>   
     