<header>
    <div id="header_content">
        <div id="logo"><a href="index.php">Job Vacancy Posting System</a></div>
        <div id="menu">
            <a class="menu_option" id="postjob" href="postjobform.php">Post a job</a>
            <a class="menu_option" id="searchjob" href="searchjobform.php">Search for job</a>
            <a class="menu_option" id="about" href="about.php">About</a>
        </div>
    </div>
</header>